title: 焼津市公衆トイレ一覧マップ
description: 焼津市の公衆トイレ一覧マップです。ふじのくにオープンデータカタログの「焼津市_0008_公衆トイレ一覧」データを使用しています。
data_url: https://docs.google.com/spreadsheets/d/16Gnie97QMhYlGitvyPKNPH7ck7mBIEoPdCaAJ88OA28/pub?gid=1957425126&single=true&output=csv
form_url:
logo_image_url: https://geoloniamaps.github.io/pwamap/icon-pwamap.svg
background_image_url: https://geoloniamaps.github.io/pwamap/geolonia_bgimage_1920_1080.png
primary_color: "#032857"
orderby: distance
